# -*- coding: utf-8 -*-
"""Makersuite (Assignment 1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/135d8XuanWL3iMd6TrivR8kMSx3ZQdcyY
"""

pip install -q -U google-generativeai

api = input("API Key: ")

import google.generativeai as genai

import os

genai.configure(api_key=api)

model = genai.GenerativeModel('gemini-1.5-flash')

response = model.generate_content("Write a common joke in Singapore or financial news ")

print(response.text)